using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Anasayfa
{
   
    public partial class FrmOgrenciler : Form
    {

        public FrmOgrenciler()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
           // sqlDataSource1.Fill();
        }

        public void Listele()
        {
            SqlDataAdapter da = new SqlDataAdapter("select TBL_OGRENCİLER.ID,AD,SOYAD,NUMARA,KULUPAD,ORTALAMA from TBL_OGRENCİLER INNER JOIN TBL_KULUPLER ON TBL_KULUPLER.ID = TBL_OGRENCİLER.KULUP", baglanti);
            DataTable dt = new DataTable();
            da.Fill(dt);
            gridControl1.DataSource = dt;
        }

        public void lookupeditkulupler()
        {
            lookUpEdit1.Properties.NullText = "Seçiniz";
            SqlDataAdapter da = new SqlDataAdapter("select * from tbl_kulupler", baglanti);
            DataTable dt = new DataTable();
            da.Fill(dt);
            lookUpEdit1.Properties.ValueMember = "ID";
            lookUpEdit1.Properties.DisplayMember = "KULUPAD";
            lookUpEdit1.Properties.DataSource = dt;
        }




        SqlConnection baglanti = new SqlConnection(@"Data Source=ADEM;Initial Catalog=TestDevexpresOgrenciOtomasyon;User ID=sa;Password=1234");
        private void FrmOgrenciler_Load(object sender, EventArgs e)
        {
           
            Listele();
            lookupeditkulupler();

        }
        public string adi;
        public string soyadi;
        public string numarasi;
        public string kulup;
        public string gelenid;
        public string gelenortalama;
        public string yol;

        private void ad_TextChanged(object sender, EventArgs e)
        {
            adi= ad.Text;
        }

        private void soyad_TextChanged(object sender, EventArgs e)
        {
            soyadi = soyad.Text;
        }

        private void numara_TextChanged(object sender, EventArgs e)
        {
            numarasi = numara.Text;
        }

        private void lookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {
            kulup = lookUpEdit1.EditValue.ToString();
        }
        private void id_TextChanged(object sender, EventArgs e)
        {
            gelenid = id.Text;
        }
        private void ortalama_EditValueChanged(object sender, EventArgs e)
        {
            gelenortalama = ortalama.Text;
        }




        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            DataRow dr = gridView1.GetDataRow(gridView1.FocusedRowHandle);
            if(dr!=null)
            {
                id.Text = dr[0].ToString();
                ad.Text = dr[1].ToString();
                soyad.Text = dr[2].ToString();
                numara.Text = dr[3].ToString();
                ortalama.Text = dr[5].ToString();
            }
            int ortalamam = Convert.ToInt32(ortalama.Text);
            if (ortalamam>=0&&ortalamam<45)
            {
                ratingControl1.EditValue = 1;
            }
            if (ortalamam >=45 && ortalamam < 55)
            {
                ratingControl1.EditValue = 2;
            }
            if (ortalamam >= 55 && ortalamam < 70)
            {
                ratingControl1.EditValue = 3;
            }
            if (ortalamam >= 70 && ortalamam < 85)
            {
                ratingControl1.EditValue = 4;
            }
            if (ortalamam >= 85 && ortalamam < 100)
            {
                ratingControl1.EditValue = 5;
            }
        }

       
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            yol = pictureEdit1.GetLoadedImageLocation();
        }
    }
}
