//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciOtomasyonu.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TELEFONREHBERİ
    {
        public int ID { get; set; }
        public string ADINIZ { get; set; }
        public string SOYADINIZ { get; set; }
        public string EVTEL { get; set; }
        public string CEPTEL { get; set; }
        public string ADRES { get; set; }
        public string RESİM { get; set; }
    }
}
