//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciOtomasyonu.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDevexpresOgrenciOtomasyonEntities3 : DbContext
    {
        public TestDevexpresOgrenciOtomasyonEntities3()
            : base("name=TestDevexpresOgrenciOtomasyonEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_TELEFONREHBERİ> TBL_TELEFONREHBERİ { get; set; }
    }
}
